# Generated by Django 2.2.5 on 2022-03-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name=())),
                ('people', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
