# Generated by Django 2.2.5 on 2022-03-03 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractTimeStampedModel',
        ),
    ]
